## Simple usecase of the API

In [23]:
import tubeulator as tb
# import geopandas
modes = tb.fetch.line.meta_modes()

In [12]:
tb.load_lines().sample(3)

shape: (3, 2)
┌──────┬──────────┐
│ Mode ┆ Name     │
│ ---  ┆ ---      │
│ str  ┆ str      │
╞══════╪══════════╡
│ tube ┆ central  │
│ tube ┆ bakerloo │
│ tram ┆ tram     │
└──────┴──────────┘

In [56]:
tb.load_lines_by_station().sample(3)

shape: (3, 3)
┌─────────────────┬───────────────────────┬────────────────┐
│ StationUniqueId ┆ Lines                 ┆ StationName    │
│ ---             ┆ ---                   ┆ ---            │
│ str             ┆ list[str]             ┆ str            │
╞═════════════════╪═══════════════════════╪════════════════╡
│ 910GSLADEGN     ┆ ["thameslink"]        ┆ Slade Green    │
│ HUBCYP          ┆ ["london-overground"] ┆ Crystal Palace │
│ 940GZZLULBN     ┆ ["bakerloo"]          ┆ Lambeth North  │
└─────────────────┴───────────────────────┴────────────────┘

In [53]:
tb.load_platform_services().sample(2)

shape: (2, 5)
┌───────────────────┬───────────────────┬───────────────────┬──────────────────┬───────────────────┐
│ PlatformUniqueId  ┆ StopAreaNaptanCod ┆ Line              ┆ DirectionTowards ┆ PlatformServiceGr │
│ ---               ┆ e                 ┆ ---               ┆ ---              ┆ oupName           │
│ str               ┆ ---               ┆ str               ┆ str              ┆ ---               │
│                   ┆ str               ┆                   ┆                  ┆ str               │
╞═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╪═══════════════════╡
│ 940GZZLULGN-Plat0 ┆ 940GZZLULGN       ┆ central           ┆ null             ┆ null              │
│ 3-WB-central      ┆                   ┆                   ┆                  ┆                   │
│ 910GWHHRTLA-Plat0 ┆ 910GWHHRTLA       ┆ london-overground ┆ Liverpool Street ┆ null              │
│ 1-SB-london-o…    ┆                   ┆                   ┆                  ┆                   │
└───────────────────┴───────────────────┴───────────────────┴──────────────────┴───────────────────┘

In [57]:
tb.load_station_points().sample(3)

shape: (3, 8)
┌────────────────┬────────────────┬──────────┬────────┬───────┬──────────┬──────────┬──────────────┐
│ UniqueId       ┆ StationUniqueI ┆ AreaName ┆ AreaId ┆ Level ┆ Lat      ┆ Lon      ┆ FriendlyName │
│ ---            ┆ d              ┆ ---      ┆ ---    ┆ ---   ┆ ---      ┆ ---      ┆ ---          │
│ str            ┆ ---            ┆ str      ┆ i64    ┆ i64   ┆ f64      ┆ f64      ┆ str          │
│                ┆ str            ┆          ┆        ┆       ┆          ┆          ┆              │
╞════════════════╪════════════════╪══════════╪════════╪═══════╪══════════╪══════════╪══════════════╡
│ 940GZZLUWYP-10 ┆ 940GZZLUWYP    ┆ MET1     ┆ 1      ┆ 0     ┆ 51.56352 ┆ -0.2796  ┆ MET1         │
│ 00257-MET1-1   ┆                ┆          ┆        ┆       ┆          ┆          ┆              │
│ 940GZZLUMED-10 ┆ 940GZZLUMED    ┆ DisEB    ┆ 5      ┆ -2    ┆ 51.5254  ┆ -0.03327 ┆ DisEB        │
│ 00146-DisEB-5  ┆                ┆          ┆        ┆       ┆          ┆          ┆              │
│ 940GZZLUHPK-10 ┆ 940GZZLUHPK    ┆ Over     ┆ 6      ┆ -2    ┆ 51.50719 ┆ -0.20558 ┆ Over         │
│ 00113-Over-6   ┆                ┆          ┆        ┆       ┆          ┆          ┆              │
└────────────────┴────────────────┴──────────┴────────┴───────┴──────────┴──────────┴──────────────┘

In [47]:
tb.load_stations_by_line()

shape: (18, 2)
┌──────────────────┬─────────────────────────────────┐
│ Line             ┆ StationName                     │
│ ---              ┆ ---                             │
│ str              ┆ list[str]                       │
╞══════════════════╪═════════════════════════════════╡
│ metropolitan     ┆ ["Moorgate", "North Harrow", …… │
│ tram             ┆ ["Lebanon Road", "Avenue Road"… │
│ london-cable-car ┆ ["IFS Cloud Royal Docks", "IFS… │
│ piccadilly       ┆ ["Gloucester Road", "Heathrow … │
│ elizabeth        ┆ ["Acton Main Line", "Tottenham… │
│ …                ┆ …                               │
│ thameslink       ┆ ["Ravensbourne", "Hendon", … "… │
│ district         ┆ ["Gloucester Road", "Sloane Sq… │
│ bakerloo         ┆ ["South Kenton", "Harlesden", … │
│ victoria         ┆ ["Stockwell", "Oxford Circus",… │
│ circle           ┆ ["Gloucester Road", "Sloane Sq… │
└──────────────────┴─────────────────────────────────┘

In [48]:
tb.load_platform_services()

shape: (1_616, 5)
┌───────────────────┬───────────────────┬───────────────────┬──────────────────┬───────────────────┐
│ PlatformUniqueId  ┆ StopAreaNaptanCod ┆ Line              ┆ DirectionTowards ┆ PlatformServiceGr │
│ ---               ┆ e                 ┆ ---               ┆ ---              ┆ oupName           │
│ str               ┆ ---               ┆ str               ┆ str              ┆ ---               │
│                   ┆ str               ┆                   ┆                  ┆ str               │
╞═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╪═══════════════════╡
│ HUBABW-Plat01-WB- ┆ 910GABWD          ┆ national-rail     ┆ null             ┆ null              │
│ national-rail     ┆                   ┆                   ┆                  ┆                   │
│ HUBABW-Plat02-EB- ┆ 910GABWD          ┆ national-rail     ┆ null             ┆ null              │
│ national-rail     ┆                   ┆                   ┆                  ┆                   │
│ HUBABW-Plat03-WB- ┆ 910GABWD          ┆ elizabeth         ┆ null             ┆ null              │
│ elizabeth         ┆                   ┆                   ┆                  ┆                   │
│ HUBABW-Plat04-WB- ┆ 910GABWD          ┆ elizabeth         ┆ null             ┆ null              │
│ elizabeth         ┆                   ┆                   ┆                  ┆                   │
│ 910GACTNCTL-Plat0 ┆ 910GACTNCTL       ┆ london-overground ┆ Richmond         ┆ null              │
│ 1-WB-london-o…    ┆                   ┆                   ┆                  ┆                   │
│ …                 ┆ …                 ┆ …                 ┆ …                ┆ …                 │
│ 940GZZBPSUST-Plat ┆ 940GZZBPSUST      ┆ northern          ┆ null             ┆ null              │
│ 02-NB-norther…    ┆                   ┆                   ┆                  ┆                   │
│ 940GZZNEUGST-Plat ┆ 940GZZNEUGST      ┆ northern          ┆ null             ┆ null              │
│ 01-NB-norther…    ┆                   ┆                   ┆                  ┆                   │
│ 940GZZNEUGST-Plat ┆ 940GZZNEUGST      ┆ northern          ┆ null             ┆ null              │
│ 02-SB-norther…    ┆                   ┆                   ┆                  ┆                   │
│ 910GBKRVS-Plat01- ┆ 910GBKRVS         ┆ london-overground ┆ null             ┆ null              │
│ WB-london-ove…    ┆                   ┆                   ┆                  ┆                   │
│ 910GBKRVS-Plat02- ┆ 910GBKRVS         ┆ london-overground ┆ null             ┆ null              │
│ WB-london-ove…    ┆                   ┆                   ┆                  ┆                   │
└───────────────────┴───────────────────┴───────────────────┴──────────────────┴───────────────────┘

In [ ]:
tb.fetch.line.arrivals_by_ids(id='london-cable-car')

In [154]:
tb.load_station_points().with_columns(
    n_obs = pl.count().over(pl.col("AreaName"), pl.col("AreaId"))
).sort("n_obs")

/var/folders/r5/1cdq52mn21zdnqzl0fvp44zw0000gn/T/ipykernel_85447/2484976830.py:2: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
  n_obs = pl.count().over(pl.col("AreaName"), pl.col("AreaId"))

shape: (3_923, 9)
┌──────────────┬──────────────┬──────────┬────────┬───┬──────────┬──────────┬──────────────┬───────┐
│ UniqueId     ┆ StationUniqu ┆ AreaName ┆ AreaId ┆ … ┆ Lat      ┆ Lon      ┆ FriendlyName ┆ n_obs │
│ ---          ┆ eId          ┆ ---      ┆ ---    ┆   ┆ ---      ┆ ---      ┆ ---          ┆ ---   │
│ str          ┆ ---          ┆ str      ┆ i64    ┆   ┆ f64      ┆ f64      ┆ str          ┆ u32   │
│              ┆ str          ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
╞══════════════╪══════════════╪══════════╪════════╪═══╪══════════╪══════════╪══════════════╪═══════╡
│ 910GACTNCTL- ┆ 910GACTNCTL  ┆ AC       ┆ 3      ┆ … ┆ 51.50862 ┆ -0.26351 ┆ AC           ┆ 1     │
│ 1001002-AC-3 ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ 910GACTNCTL- ┆ 910GACTNCTL  ┆ ENTR     ┆ 7      ┆ … ┆ 51.50892 ┆ -0.2626  ┆ ENTR         ┆ 1     │
│ 1001002-ENTR ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ -7           ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ 910GACTONML- ┆ 910GACTONML  ┆ AC-B     ┆ 3      ┆ … ┆ 51.51732 ┆ -0.26669 ┆ AC-B         ┆ 1     │
│ 1001003-AC-B ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ -3           ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ 910GACTONML- ┆ 910GACTONML  ┆ AC-S     ┆ 6      ┆ … ┆ 51.5168  ┆ -0.26736 ┆ AC-S         ┆ 1     │
│ 1001003-AC-S ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ -6           ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ 910GANERLEY- ┆ 910GANERLEY  ┆ AcAne    ┆ 3      ┆ … ┆ 51.41221 ┆ -0.06544 ┆ AcAne        ┆ 1     │
│ 1001007-AcAn ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ e-3          ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ …            ┆ …            ┆ …        ┆ …      ┆ … ┆ …        ┆ …        ┆ …            ┆ …     │
│ HUBWMB-10002 ┆ HUBWMB       ┆ Bus      ┆ 1      ┆ … ┆ 51.55255 ┆ -0.29696 ┆ Bus          ┆ 283   │
│ 56-Bus-1     ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ HUBWRU-10002 ┆ HUBWRU       ┆ Bus      ┆ 1      ┆ … ┆ 51.56986 ┆ -0.4381  ┆ Bus          ┆ 283   │
│ 67-Bus-1     ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ HUBWSM-10002 ┆ HUBWSM       ┆ Bus      ┆ 1      ┆ … ┆ 51.50125 ┆ -0.12377 ┆ Bus          ┆ 283   │
│ 66-Bus-1     ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ HUBZMG-10001 ┆ HUBZMG       ┆ Bus      ┆ 1      ┆ … ┆ 51.5179  ┆ -0.0883  ┆ Bus          ┆ 283   │
│ 49-Bus-1     ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
│ HUBZWL-10002 ┆ HUBZWL       ┆ Bus      ┆ 1      ┆ … ┆ 51.51915 ┆ -0.05876 ┆ Bus          ┆ 283   │
│ 68-Bus-1     ┆              ┆          ┆        ┆   ┆          ┆          ┆              ┆       │
└──────────────┴──────────────┴──────────┴────────┴───┴──────────┴──────────┴──────────────┴───────┘

In [5]:
df["ModeName"].unique()

shape: (4,)
Series: 'ModeName' [str]
[
	"tram"
	"dlr"
	"elizabeth-line"
	"overground"
]

In [187]:
df.describe()

shape: (9, 21)
┌────────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬──────────┬────────┐
│ statistic  ┆ Id         ┆ OperationT ┆ VehicleId ┆ … ┆ ExpectedA ┆ TimeToLiv ┆ ModeName ┆ Timing │
│ ---        ┆ ---        ┆ ype        ┆ ---       ┆   ┆ rrival    ┆ e         ┆ ---      ┆ ---    │
│ str        ┆ str        ┆ ---        ┆ str       ┆   ┆ ---       ┆ ---       ┆ str      ┆ f64    │
│            ┆            ┆ f64        ┆           ┆   ┆ str       ┆ str       ┆          ┆        │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪════════╡
│ count      ┆ 4619       ┆ 4619.0     ┆ 4619      ┆ … ┆ 4619      ┆ 4619      ┆ 4619     ┆ 4619.0 │
│ null_count ┆ 0          ┆ 0.0        ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0        ┆ 0.0    │
│ mean       ┆ null       ┆ 1.0        ┆ null      ┆ … ┆ 2024-10-0 ┆ 2024-10-0 ┆ null     ┆ null   │
│            ┆            ┆            ┆           ┆   ┆ 5 14:51:2 ┆ 5 14:49:5 ┆          ┆        │
│            ┆            ┆            ┆           ┆   ┆ 6.922710+ ┆ 0.941762+ ┆          ┆        │
│            ┆            ┆            ┆           ┆   ┆ 00:…      ┆ 00:…      ┆          ┆        │
│ std        ┆ null       ┆ 0.0        ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null   │
│ min        ┆ -100082548 ┆ 1.0        ┆           ┆ … ┆ 2024-10-0 ┆ 2024-10-0 ┆ dlr      ┆ null   │
│            ┆ 9          ┆            ┆           ┆   ┆ 5 14:00:0 ┆ 5 13:59:5 ┆          ┆        │
│            ┆            ┆            ┆           ┆   ┆ 4+00:00   ┆ 4+00:00   ┆          ┆        │
│ 25%        ┆ null       ┆ 1.0        ┆ null      ┆ … ┆ 2024-10-0 ┆ 2024-10-0 ┆ null     ┆ null   │
│            ┆            ┆            ┆           ┆   ┆ 5 14:17:0 ┆ 5 14:14:5 ┆          ┆        │
│            ┆            ┆            ┆           ┆   ┆ 0+00:00   ┆ 8+00:00   ┆          ┆        │
│ 50%        ┆ null       ┆ 1.0        ┆ null      ┆ … ┆ 2024-10-0 ┆ 2024-10-0 ┆ null     ┆ null   │
│            ┆            ┆            ┆           ┆   ┆ 5 14:49:0 ┆ 5 14:46:1 ┆          ┆        │
│            ┆            ┆            ┆           ┆   ┆ 0+00:00   ┆ 0+00:00   ┆          ┆        │
│ 75%        ┆ null       ┆ 1.0        ┆ null      ┆ … ┆ 2024-10-0 ┆ 2024-10-0 ┆ null     ┆ null   │
│            ┆            ┆            ┆           ┆   ┆ 5 15:24:0 ┆ 5 15:22:0 ┆          ┆        │
│            ┆            ┆            ┆           ┆   ┆ 0+00:00   ┆ 8+00:00   ┆          ┆        │
│ max        ┆ 999995768  ┆ 1.0        ┆ 2565      ┆ … ┆ 2024-10-0 ┆ 2024-10-0 ┆ tram     ┆ null   │
│            ┆            ┆            ┆           ┆   ┆ 5 15:59:0 ┆ 5 15:58:1 ┆          ┆        │
│            ┆            ┆            ┆           ┆   ┆ 0+00:00   ┆ 5+00:00   ┆          ┆        │
└────────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴──────────┴────────┘

In [203]:
(
    df
    .select("StationName", "DestinationName", "VehicleId","ExpectedArrival", "TimeToLive")
    .filter(pl.col("VehicleId")=="2557")
    .sort("ExpectedArrival")
)

shape: (14, 5)
┌──────────────────┬─────────────────┬───────────┬─────────────────────┬───────────────────────────┐
│ StationName      ┆ DestinationName ┆ VehicleId ┆ ExpectedArrival     ┆ TimeToLive                │
│ ---              ┆ ---             ┆ ---       ┆ ---                 ┆ ---                       │
│ str              ┆ str             ┆ str       ┆ datetime[μs, UTC]   ┆ datetime[μs, UTC]         │
╞══════════════════╪═════════════════╪═══════════╪═════════════════════╪═══════════════════════════╡
│ Morden Road      ┆ Elmers End      ┆ 2557      ┆ 2024-10-05 14:03:50 ┆ 2024-10-05 14:03:50 UTC   │
│                  ┆                 ┆           ┆ UTC                 ┆                           │
│ Belgrave Walk    ┆ Elmers End      ┆ 2557      ┆ 2024-10-05 14:05:14 ┆ 2024-10-05 14:05:14 UTC   │
│                  ┆                 ┆           ┆ UTC                 ┆                           │
│ Phipps Bridge    ┆ Elmers End      ┆ 2557      ┆ 2024-10-05 14:05:50 ┆ 2024-10-05 14:05:50 UTC   │
│                  ┆                 ┆           ┆ UTC                 ┆                           │
│ Mitcham          ┆ Elmers End      ┆ 2557      ┆ 2024-10-05 14:07:44 ┆ 2024-10-05 14:07:44 UTC   │
│                  ┆                 ┆           ┆ UTC                 ┆                           │
│ Mitcham Junction ┆ Elmers End      ┆ 2557      ┆ 2024-10-05 14:10:44 ┆ 2024-10-05 14:10:44 UTC   │
│                  ┆                 ┆           ┆ UTC                 ┆                           │
│ …                ┆ …               ┆ …         ┆ …                   ┆ …                         │
│ Wandle Park      ┆ Elmers End      ┆ 2557      ┆ 2024-10-05 14:18:44 ┆ 2024-10-05 14:18:44 UTC   │
│                  ┆                 ┆           ┆ UTC                 ┆                           │
│ Reeves Corner    ┆ Elmers End      ┆ 2557      ┆ 2024-10-05 14:20:44 ┆ 2024-10-05 14:20:44 UTC   │
│                  ┆                 ┆           ┆ UTC                 ┆                           │
│ Centrale         ┆ Elmers End      ┆ 2557      ┆ 2024-10-05 14:22:44 ┆ 2024-10-05 14:22:44 UTC   │
│                  ┆                 ┆           ┆ UTC                 ┆                           │
│ West Croydon     ┆ Elmers End      ┆ 2557      ┆ 2024-10-05 14:24:44 ┆ 2024-10-05 14:24:44 UTC   │
│                  ┆                 ┆           ┆ UTC                 ┆                           │
│ Wellesley Road   ┆ Elmers End      ┆ 2557      ┆ 2024-10-05 14:27:44 ┆ 2024-10-05 14:27:44 UTC   │
│                  ┆                 ┆           ┆ UTC                 ┆                           │
└──────────────────┴─────────────────┴───────────┴─────────────────────┴───────────────────────────┘

## Final Code to Grab data

In [2]:

## https://github.com/lmmx/tubeulator
import pandas as pd
import polars as pl
import igraph as ig
import tubeulator

## lines?
lines = tubeulator.load_lines()

## get eveything but nationa-rail way
arrivable_line_names = lines.filter(pl.col("Name") != "national-rail")["Name"].unique().sort().to_list()
query= ",".join(arrivable_line_names)

## query all lines; clean result list into a record eventual pandas dataframe.
result_models = tubeulator.fetch.line.arrivals_by_ids(ids=query)
results = [rm.model_dump() for rm in result_models]
df = pl.DataFrame(results)


## create an edge and node data from transport
time_edge = (df
    # .select("StationName", "DestinationName", "VehicleId","ExpectedArrival", "TimeToLive")
    .with_columns(
        time_travel = pl.col("ExpectedArrival") -
        pl.col("ExpectedArrival")
        .shift(1)
        .over(order_by = pl.col("ExpectedArrival"), partition_by = pl.col("VehicleId")),
        prev_station = pl.col("StationName")
        .shift(1)
        .over(order_by = pl.col("ExpectedArrival"), partition_by = pl.col("VehicleId"))
    )
    .rename(
        {"prev_station":"from_station","StationName":"to_station"}
    )
    .select(
       "from_station","to_station","time_travel", "VehicleId", "ExpectedArrival", "ModeName"
    )
    .filter(pl.col("time_travel").is_not_null())
)

## filter down to overground only
overground_edge = time_edge.sql("select * from self where ModeName = 'overground'").to_pandas()


## swap names with integer ids
unique_station = pd.concat([
    overground_edge['from_station'],
    overground_edge['to_station']
]).unique()

## create a unique mapping directionary with name being key, value being integer
map_rev = pd.DataFrame(dict(name = pd.Series(unique_station))).to_dict().get('name')
mapping ={val:key for key,val in map_rev.items()}

## create an edge list from igraph
edge_list = overground_edge.replace(
    {'from_station':mapping, 'to_station':mapping}
) # !pip install rpy2
graph = ig.Graph.DataFrame(
    edge_list
)
graph.vs['name'] = [x[1] for x in map_rev.items()]

/var/folders/r5/1cdq52mn21zdnqzl0fvp44zw0000gn/T/ipykernel_72967/2681134465.py:56: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  edge_list = overground_edge.replace(

In [3]:
## input a station A & B
stationA = "Rectory Road Rail Station"
stationB = "Edmonton Green Rail Station"


## get shortest path
# !pip install pycairo
import textwrap 

start = mapping.get(stationA)
end = mapping.get(stationB)

## note this only get you the last station to pass through
path = graph.get_shortest_path(start,end)
print(textwrap.fill(' -> '.join(unique_station[path]),80))

Rectory Road Rail Station -> Stoke Newington Rail Station -> Stamford Hill Rail
Station -> Seven Sisters Rail Station -> Bruce Grove Rail Station -> White Hart
Lane Rail Station -> Silver Street Rail Station -> Edmonton Green Rail Station

In [3]:
## export two to work
# overground_edge.to_parquet("overgroud_edge.parquet")
# overground_edge.to_csv("overgroud_edge.csv")

In [22]:

from ipysigma import Sigma
import numpy as np

## this line because Sigma don't like you put time delta
if type(graph.es['time_travel'][0]) != float:
      graph.es['time_travel'] = [e.total_seconds()/60 for e in graph.es['time_travel']]

## color route station 
assert len(graph.es[path]) == len(path)
graph.vs[path]['color'] = ['route']
graph.vs['color'] = ['' if e is None else e for e in graph.vs['color']]
## visualize use sigma net
Sigma(graph
      # , node_size=graph.vs.degree()
      , edge_weight=graph.es['time_travel']
      , edge_size =1/np.array(graph.es['time_travel'])
      , node_label = graph.vs['name']
      , node_color = graph.vs['color']
)

Sigma(ig.Graph with 109 nodes and 2,280 edges)

In [ ]:
## graph visualisation using igraph
import networkx as nx
from pyvis.network import Network

## easy way is use networkx instead of igraph;
graph_nx = nx.from_edgelist(graph.get_edgelist())
net = Network(notebook=True
              , cdn_resources='remote') 
net.from_nx(graph_nx)
net.show('nx.html')

In [7]:

## export closest to data structure that match de
gdict = graph.to_dict_list()
## this code will work just dont return anything
[gdict[0][i].update({"id":i}) for i in range(len(gdict[0]))]
json_data = {"nodes":gdict[0], "links":gdict[1]}

In [18]:
## use a new module
## use d3 visualisation from javascript library
from IPython.display import display, HTML
import d3force
import importlib
importlib.reload(d3force)
import json 

if type(json_data.get('links')[0].get('ExpectedArrival')) != str:
    [record.update({'ExpectedArrival':record.get('ExpectedArrival').strftime('%Y-%m-%d %H:%M:%S')}) for record in json_data.get('links')]
json_data

x = d3force.vis(json_data, -2)

display(HTML(x))